// <auto-generated />
namespace CoreEntites.DomainContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changeconnectionforFK : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeconnectionforFK));
        
        string IMigrationMetadata.Id
        {
            get { return "201712031639062_change connection for FK"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
